name: CI

on:
  pull_request:

  push:
    branches:
      - main

env:
  CRYSTAL_VERSION: '1.0.0'
  SELENIUM_BROWSER_URL: 'http://localhost:4444'
  MINIFY_JS: true
  CI: true

jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: oprypin/install-crystal@v1
        with:
          crystal: ${{ env.CRYSTAL_VERSION }}
      - run: shards install --ignore-crystal-version
      - run: crystal tool format --check

  Specs:
    needs: [Linter]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: oprypin/install-crystal@v1
        with:
          crystal: ${{ env.CRYSTAL_VERSION }}
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm i -g uglify-js
      - run: shards install --ignore-crystal-version
      - run: crystal spec
